name: macOS Application Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4  # Updated to version 4

    - name: Set up Python
      uses: actions/setup-python@v4  # Use version 4
      with:
        python-version: '3.12'  # You can specify a version you need

    - name: Install py2app
      run: |
        python -m pip install --upgrade pip
        pip install py2app

    - name: Build the app
      run: |
        python setup.py py2app
      working-directory: ./New Folder  # Specify the directory containing your files

    - name: Archive the built app
      uses: actions/upload-artifact@v4  # Ensure right version of the artifact uploader is used
      with:
        name: SearchTaskApp
        path: ./New Folder/dist/*.app  # Path to your app bundle
