name: macOS Application Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Adjust as needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Clean build directory
      run: |
        rm -rf './New Folder/build/'
        rm -rf './New Folder/dist/'

    - name: Build the app
      run: |
        python -m build --wheel
      working-directory: './New Folder'

    - name: Prepare app
      run: |
        mv './New Folder/dist' './dist'

    - name: Archive the built app
      uses: actions/upload-artifact@v3
      with:
        name: SearchTaskApp
        path: './dist/*.app'
